name: sample-monorepo

static_sites:
- name: frontend
  environment_slug: html
  github:
    repo: jg132/sample-monorepo
    branch: main
    deploy_on_push: true
  source_dir: frontends/reactapp
  index_document: hello.html
  error_document: error.html
  routes:
  - path: /frontends/reactapp

services:
- name: api
  environment_slug: php
  github:
    repo: jg132/sample-monorepo
    branch: main
    deploy_on_push: true
  source_dir: backends/api
  routes:
  - path: /backends/api